### ISSUE TITLE
consider pipx as installation method

### ISSUE THREAD

**Issue by cs01** [sdispater/poetry#677]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

[pipx](https://github.com/cs01/pipx) is a new project I started that replaces pipsi. pipsi is great but development and support has stopped, so I started pipx with the goal of using modern Python (venv's only, Python 3.6+), improving the UX, adding new commands, and adding an option to run applications in one-time environments that are deleted after exit.

pipx installs poetry nicely and might be a good alternate way to recommend poetry be installed.

 Attached is a short video demonstrating its installation.
![pipx_poetry_demo](https://user-images.githubusercontent.com/5715368/49053453-04f71680-f1a5-11e8-8905-2e3e8358b162.gif)

https://github.com/cs01/pipx

**Comment by gonvaled** [comment]
This seems to be working for me. The official install method fails in Linux Mint 19 Tara

**Comment by batisteo** [comment]
Is your proposition is to replace
```bash
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
```
by
```bash
curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python3
pipx install poetry
```
:question:

**Comment by sdispater** [comment]
@cs01 I'd gladly review and merge a PR that adds (or replace `pipsi`) `pipx` to the documentation. However it's unlikely that it will replace the recommended installer. Here are a few reasons:


- The installer installs Poetry in such a way that it is completely isolated from the rest of the system (vendored dependencies). That way its dependencies are fixed and there is no risk of dependencies being removed or updated by the installation of another tool. I know `pipx` installs in a virtualenv but this is not the same thing as having a fixed set of dependencies.
- If you install it via `pipx` (like with `pip`), Poetry will only be aware of the Python executable it has been installed for and as such will not be able to pick up the proper python version set by a tool like pyenv. Let's say I execute `pipx install poetry` for `pipx` installed for Python 3.7.1, the `poetry` command will be linked with Python 3.7.1. So if I later do `pyenv shell 3.6`, `poetry` will still see Python 3.7.1.

**Comment by bersace** [comment]
Note that poetry is incompatible with docker-compose. They conflict on jsonschema version. That's a good reason to have poetry in it's own venv.

**Comment by funkyfuture** [comment]
> Note that poetry is incompatible with docker-compose. They conflict on jsonschema version. That's a good reason to have poetry in it's own venv. I just wished `.poetry` was in `.local` or `.cache` because i don't like to clutter my home.

well, you'd have to install Docker-Compose w/ `pipx`.

**Comment by RoelantStegmann** [comment]
> If you install it via pipx (like with pip), Poetry will only be aware of the Python executable it has been installed for and as such will not be able to pick up the proper python version set by a tool like pyenv. Let's say I execute pipx install poetry for pipx installed for Python 3.7.1, the poetry command will be linked with Python 3.7.1. So if I later do pyenv shell 3.6, poetry will still see Python 3.7.1.

Yes, I had this issue. It is sad, because installing poetry in each conda env feels like overdoing it.

**Comment by fgervais** [comment]
@sdispater does the `pipx` installation still have the above-mentioned shortcomings compared to the new `install-poetry.py` script?

**Comment by shelper** [comment]
> @cs01 I'd gladly review and merge a PR that adds (or replace `pipsi`) `pipx` to the documentation. However it's unlikely that it will replace the recommended installer. Here are a few reasons:
> 
> * The installer installs Poetry in such a way that it is completely isolated from the rest of the system (vendored dependencies). That way its dependencies are fixed and there is no risk of dependencies being removed or updated by the installation of another tool. I know `pipx` installs in a virtualenv but this is not the same thing as having a fixed set of dependencies.
> * If you install it via `pipx` (like with `pip`), Poetry will only be aware of the Python executable it has been installed for and as such will not be able to pick up the proper python version set by a tool like pyenv. Let's say I execute `pipx install poetry` for `pipx` installed for Python 3.7.1, the `poetry` command will be linked with Python 3.7.1. So if I later do `pyenv shell 3.6`, `poetry` will still see Python 3.7.1.

well then if i use the `https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py` to install poetry, then my poetry is linked to whatever the python env that runs this script. so if i install poetry when python3.7 is active, then i don't have poetry in my python3.6 env ... bascially i need to install poetry for all of my python versions...

this may not be desirable, poetry is just a tool that can be system wide, if i need to change my python version, i can do `poetry env use 3.x`, and i think that is more convenient

**Comment by wtfzambo** [comment]
> > @cs01 I'd gladly review and merge a PR that adds (or replace `pipsi`) `pipx` to the documentation. However it's unlikely that it will replace the recommended installer. Here are a few reasons:
> > 
> > * The installer installs Poetry in such a way that it is completely isolated from the rest of the system (vendored dependencies). That way its dependencies are fixed and there is no risk of dependencies being removed or updated by the installation of another tool. I know `pipx` installs in a virtualenv but this is not the same thing as having a fixed set of dependencies.
> > * If you install it via `pipx` (like with `pip`), Poetry will only be aware of the Python executable it has been installed for and as such will not be able to pick up the proper python version set by a tool like pyenv. Let's say I execute `pipx install poetry` for `pipx` installed for Python 3.7.1, the `poetry` command will be linked with Python 3.7.1. So if I later do `pyenv shell 3.6`, `poetry` will still see Python 3.7.1.
> 
> well then if i use the `https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py` to install poetry, then my poetry is linked to whatever the python version that runs this script. so poetry is linked to this python version anyway, i dont see how this is different from using pipx... anyway just a comment, maybe i missed something, but either way, poetry should be installed by the new installation script

For me is exactly the same. Tested both in windows and linux, poetry is tied to the python version it's been used to install it.

The only way I found to specify a different one when creating a virtual environment is to run `poetry  env use your_python_version_here`. Activating it (with pyenv or scoop) when running `poetry new` or `poetry init` doesn't seem to do anything.

**Comment by namanrawal47** [comment]
The best way to install poetry using pipx today is:
`pipx install poetry==1.2.2`
